net.Receive( "EventVote", function()
	local index = net.ReadUInt( 4 )
	local event = EventList[index]
	local Frame = vgui.Create( "DFrame" )
	Frame:SetTitle( "" )
	Frame:SetSize( 350, 215 )
	Frame:SetPos( 10, 300 )
	Frame:SetDraggable( false )
	Frame:ShowCloseButton( false )
	Frame.Paint = function( self, w, h )
		draw.RoundedBox( 0, 0, 0, w, h, Color( 49, 53, 61, 200 ) )
	end
	local label = vgui.Create( "DLabel", Frame )
	label:Dock( TOP )
	label:SetFont( "Trebuchet24" )
	label:SetText( "Event Opportunity: "..event.Name )
	label:SetWrap( true )
	local desc = vgui.Create( "DLabel", Frame )
	desc:Dock( FILL )
	desc:DockMargin( 0, 0, 0, 10 )
	desc:SetFont( "Trebuchet18" )
	desc:SetText( event.Desc )
	desc:SetWrap( true )
	local yes = vgui.Create( "DButton", Frame )
	yes:SetText( "Vote Yes" )
	yes:SetTextColor( color_white )
	yes:SetPos( 5, 180 )
	yes:DockMargin( 0, 0, 0, 10 )
	yes:SetSize( 145, 30 )
	yes.Paint = function( self, w, h )
		draw.RoundedBox( 0, 0, 0, w, h, Color( 230, 93, 80, 255 ) )
	end
	yes.DoClick = function()
		net.Start( "EventVote" )
		net.WriteBool( true )
		net.SendToServer()
		Frame:Remove()
	end
	local no = vgui.Create( "DButton", Frame )
	no:SetText( "Vote No" )
	no:SetTextColor( color_white )
	no:Dock( BOTTOM )
	no:DockMargin( 200, 0, 0, 0 )
	no:SetSize( 145, 30 )
	no.Paint = function( self, w, h )
		draw.RoundedBox( 0, 0, 0, w, h, Color( 230, 93, 80, 255 ) )
	end
	no.DoClick = function()
		net.Start( "EventVote" )
		net.WriteBool( false )
		net.SendToServer()
		Frame:Remove()
	end
	surface.PlaySound( "friends/message.wav" )
	timer.Simple( 30, function()
		if IsValid( Frame ) then
			Frame:Remove()
		end
	end )
end )
