
if SERVER then
	hook.Add( "InitPostEntity", "LoadNPCsCityRP", function()
		timer.Simple( 10, function()
			if game.GetMap() == "rp_rockford_v2b" then
				local drug = ents.Create( "rp_dealer" )
				drug:SetPos( Vector( -14461, 2342, 392 ) )
				drug:SetAngles( Angle( 0, -90, 0 ) )
				drug:SetModel( "models/player/group03/male_08.mdl" )
				drug:Spawn()
				local bank = ents.Create("banker_npc")
				bank:SetPos( Vector( -1492, 7941, 544 ) )
				bank:SetAngles( Angle( 0, 0, 0 ) )
				bank:SetModel( "models/player/group01/male_02.mdl" )
				bank:Spawn()
				local release = ents.Create("breakout_npc")
				release:SetPos( Vector( -8687, -5565, 8 ) )
				release:SetAngles( Angle( 0, -90, 0 ) )
				release:SetModel( "models/Humans/Group03/male_03.mdl" )
				release:Spawn()
			end

			if game.GetMap() == "rp_chaos_city_v33x_03" then
				local drug = ents.Create( "rp_dealer" )
				drug:SetPos( Vector( -5883, 15892, -1490 ) )
				drug:SetAngles( Angle( 0, -90, 0 ) )
				drug:SetModel( "models/player/group03/male_08.mdl" )
				drug:Spawn()
				local bank = ents.Create("banker_npc")
				bank:SetPos( Vector( -6735, 13187, -1482 ) )
				bank:SetAngles( Angle( 0, 0, 0 ) )
				bank:SetModel( "models/player/group01/male_02.mdl" )
				bank:Spawn()
				local release = ents.Create("breakout_npc")
				release:SetPos( Vector( 3537, -4467, -1869 ) )
				release:SetAngles( Angle( 0, 90, 0 ) )
				release:SetModel( "models/Humans/Group03/male_03.mdl" )
				release:Spawn()
			end

			if game.GetMap() == "rp_evocity2_v5p" then
				local drug = ents.Create( "rp_dealer" )
				drug:SetPos( Vector( -7543, 445, 140 ) )
				drug:SetAngles( Angle( 0, 0, 0 ) )
				drug:SetModel( "models/player/group03/male_08.mdl" )
				drug:Spawn()
				local bank = ents.Create("banker_npc")
				bank:SetPos( Vector( 5689, 9327, 64 ) )
				bank:SetAngles( Angle( 0, 0, 0 ) )
				bank:SetModel( "models/player/group01/male_02.mdl" )
				bank:Spawn()
				local release = ents.Create("breakout_npc")
				release:SetPos( Vector( -242, -1951, 76 ) )
				release:SetAngles( Angle( 0, 180, 0 ) )
				release:SetModel( "models/Humans/Group03/male_03.mdl" )
				release:Spawn()
			end

			if game.GetMap() == "rp_florida_v2" then
				local drug = ents.Create( "rp_dealer" )
				drug:SetPos( Vector( -4687, 8020, 136 ) )
				drug:SetAngles( Angle( 0, 0, 0 ) )
				drug:SetModel( "models/player/group03/male_08.mdl" )
				drug:Spawn()
				local bank = ents.Create("banker_npc")
				bank:SetPos( Vector( 12525, 5561, 135 ) )
				bank:SetAngles( Angle( 0, 180, 0 ) )
				bank:SetModel( "models/player/group01/male_02.mdl" )
				bank:Spawn()
				local release = ents.Create("breakout_npc")
				release:SetPos( Vector( 6468, -2716, 136 ) )
				release:SetAngles( Angle( 0, 180, 0 ) )
				release:SetModel( "models/Humans/Group03/male_03.mdl" )
				release:Spawn()
			end

			if game.GetMap() == "rp_pinescity_v2b" then
				local drug = ents.Create( "rp_dealer" )
				drug:SetPos( Vector( -10096, 11233, 96 ) )
				drug:SetAngles( Angle( 0, 180, 0 ) )
				drug:SetModel( "models/player/group03/male_08.mdl" )
				drug:Spawn()
				local bank = ents.Create("banker_npc")
				bank:SetPos( Vector( 13856, 10794, 88 ) )
				bank:SetAngles( Angle( 0, -90, 0 ) )
				bank:SetModel( "models/player/group01/male_02.mdl" )
				bank:Spawn()
				local release = ents.Create("breakout_npc")
				release:SetPos( Vector( -5229, 12070, 120 ) )
				release:SetAngles( Angle( 0, 0, 0 ) )
				release:SetModel( "models/Humans/Group03/male_03.mdl" )
				release:Spawn()
			end

			if game.GetMap() == "rp_newexton2_v4h" then
				local drug = ents.Create( "rp_dealer" )
				drug:SetPos( Vector( -6176, -11929, -520 ) )
				drug:SetAngles( Angle( 0, 0, 0 ) )
				drug:SetModel( "models/player/group03/male_08.mdl" )
				drug:Spawn()
				local bank = ents.Create("banker_npc")
				bank:SetPos(Vector( -4215, -11715, -512 ) )
				bank:SetAngles( Angle( 0, 180, 0 ) )
				bank:SetModel( "models/player/group01/male_02.mdl" )
				bank:Spawn()
				local release = ents.Create("breakout_npc")
				release:SetPos( Vector( -6440, 8162, 1088 ) )
				release:SetAngles( Angle( 0, -90, 0 ) )
				release:SetModel( "models/Humans/Group03/male_03.mdl" )
				release:Spawn()
			end
		end )
	end )
end